name: word_weather
description: "Weather Application."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.3
  firebase_core: ^2.24.1
  flutter_animate: ^4.3.0
  firebase_auth: ^4.15.1
  firebase_storage: ^11.5.4
  cloud_firestore: ^4.13.4
  http: ^1.1.2
  icons_plus: ^4.0.0
  carousel_slider: ^4.2.1
  get: ^4.6.6
  path_provider: ^2.1.1
  chatview: ^1.3.1
  google_nav_bar: ^5.0.6
  flutter_native_splash: ^2.3.8
  awesome_snackbar_content: ^0.1.3
  syncfusion_flutter_charts: ^23.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/country_flags/
